### ISSUE TITLE
Проверить разделы по лесному инспектору

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/docs_forestinspector#1]
Проверить:
1. Алиасы рисунков и разделов
2. Стилистику и смысловую нагрузку
3. Орфографию
4. Размеры рисунков, подписи.
5. Терминология, термины и аббревиатуры

**Comment by baryshnikova131076** [comment]
Угомонись
12 Июл 2016 г. 15:35 пользователь "Dmitry Baryshnikov" <
notifications@github.com> написал:
